name: 'SAST validator'
author: 'michelleamesquita'
description: 'Using python to verify vulnerabilities into code'
inputs:
  path:
    required: true
    default: "."
  language:
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout repository content
      uses: actions/checkout@v2 # Checkout the repository content to github runner.

    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Pass Inputs to Shell
      run: |
                echo "INPUT_PATH=${{ inputs.path }} INPUT_LANG=${{ inputs.language }}" >> $GITHUB_ENV
      shell: bash
    - name: run Sast
      run: python sast.py -d=${{ inputs.path }} -l=${{ inputs.language }}
      shell: bash
