
on:
  push:
    branches:
    - main

jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: michelleamesquita/sast:latest
                options: -v $PWD/:/app sast -d=. -l=python
                
