
on:
  push:
    branches:
    - main

jobs:
  sast_job:
    runs-on: ubuntu-latest
    name: SAST Validator
    steps:
      - name: SAST validator
        uses: michelleamesquita/sast-validator@v30
        with:
          path: .
          language: python
